const DB_NAME = "essayExamDB_v2";
const DB_VERSION = 1;
const STORES = { problems: "problems", attempts: "attempts", settings: "settings" };
const SUBJECTS = ["형법", "형사소송법", "행정법", "교정학"];

let db, problems = [], attempts = [];
let questionImageData = "", modelImageData = "";
let activeSession = null, timerHandle = null, zoom = 1, currentAttemptSnapshot = null;
const $ = (id) => document.getElementById(id);

function uuid(){ return (crypto.randomUUID && crypto.randomUUID()) || `id_${Date.now()}_${Math.random().toString(16).slice(2)}`; }
function nowIso(){ return new Date().toISOString(); }
function fmtTime(ms){ ms=Math.max(0,Math.floor(ms||0)); const s=Math.floor(ms/1000), h=Math.floor(s/3600), m=Math.floor((s%3600)/60), sec=s%60; return h?`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`:`${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`; }
function dateLabel(iso){ if(!iso)return "-"; const d=new Date(iso); if(Number.isNaN(d.getTime()))return "-"; return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")} ${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`; }
function escapeHtml(s){ return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])); }
function toast(msg){ $("toast").textContent=msg; $("toast").classList.remove("hidden"); clearTimeout(toast._t); toast._t=setTimeout(()=>$("toast").classList.add("hidden"),2200); }

function openDB(){ return new Promise((resolve,reject)=>{ const req=indexedDB.open(DB_NAME,DB_VERSION); req.onupgradeneeded=()=>{ const d=req.result; if(!d.objectStoreNames.contains(STORES.problems))d.createObjectStore(STORES.problems,{keyPath:"id"}); if(!d.objectStoreNames.contains(STORES.attempts)){ const s=d.createObjectStore(STORES.attempts,{keyPath:"id"}); s.createIndex("problemId","problemId",{unique:false}); } if(!d.objectStoreNames.contains(STORES.settings))d.createObjectStore(STORES.settings,{keyPath:"key"}); }; req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error); }); }
function store(name,mode="readonly"){ return db.transaction(name,mode).objectStore(name); }
function getAll(name){ return new Promise((resolve,reject)=>{ const req=store(name).getAll(); req.onsuccess=()=>resolve(req.result||[]); req.onerror=()=>reject(req.error); }); }
function put(name,value){ return new Promise((resolve,reject)=>{ const req=store(name,"readwrite").put(value); req.onsuccess=()=>resolve(value); req.onerror=()=>reject(req.error); }); }
function del(name,key){ return new Promise((resolve,reject)=>{ const req=store(name,"readwrite").delete(key); req.onsuccess=()=>resolve(); req.onerror=()=>reject(req.error); }); }
function clearStore(name){ return new Promise((resolve,reject)=>{ const req=store(name,"readwrite").clear(); req.onsuccess=()=>resolve(); req.onerror=()=>reject(req.error); }); }
async function getSetting(key,fallback=null){ return await new Promise(resolve=>{ const req=store(STORES.settings).get(key); req.onsuccess=()=>resolve(req.result?.value??fallback); req.onerror=()=>resolve(fallback); }); }
async function setSetting(key,value){ await put(STORES.settings,{key,value}); }
async function loadData(){ problems=(await getAll(STORES.problems)).sort((a,b)=>(a.order??0)-(b.order??0)||a.createdAt.localeCompare(b.createdAt)); attempts=(await getAll(STORES.attempts)).sort((a,b)=>(b.completedAt||"").localeCompare(a.completedAt||"")); }

function problemAttempts(id){ return attempts.filter(a=>a.problemId===id); }
function lastAttempt(id){ return problemAttempts(id).sort((a,b)=>(b.completedAt||"").localeCompare(a.completedAt||""))[0]; }
function avgElapsed(id){ const arr=problemAttempts(id).filter(a=>a.elapsedMs); return arr.length?arr.reduce((s,a)=>s+a.elapsedMs,0)/arr.length:0; }
function titleOf(p){ return p.title || `${p.session?p.session+" ":""}${p.subject} 문제`; }
function metaOf(p){ const count=problemAttempts(p.id).length, last=lastAttempt(p.id); return `${p.subject||"-"} · ${p.session||"연도/회차 없음"} · ${p.maxScore||0}점 · 제한 ${p.timeLimitMin||0}분 · 기록 ${count}회${last?" · 최근 "+fmtTime(last.elapsedMs):""}`; }
function pointsFromText(text){ return (text||"").split(/\n+/).map(s=>s.trim()).filter(Boolean); }
function isLowScore(a,p){ if(!a||a.score===""||a.score==null)return false; const max=Number(p.maxScore||a.maxScore||0); return !!max && Number(a.score)/max<0.6; }
function isTimeOver(a,p){ const limit=Number(p.timeLimitMin||0); return !!(limit&&a?.elapsedMs&&a.elapsedMs>limit*60000); }
function hasMissedPoint(a,p){ const points=p.points?.length?p.points:pointsFromText(p.pointsText); if(!a||!points.length)return false; const checked=Array.isArray(a.checkedPoints)?a.checkedPoints.filter(Boolean).length:0; return checked<points.length; }
function filterProblems({subject="",session="",search=""}={}){ const s=(session||"").trim().toLowerCase(), q=(search||"").trim().toLowerCase(); return problems.filter(p=>{ if(subject&&p.subject!==subject)return false; if(s&&!(p.session||"").toLowerCase().includes(s))return false; if(q){ const blob=[p.title,p.pointsText,p.modelText,p.subject,p.session].join(" ").toLowerCase(); if(!blob.includes(q))return false; } return true; }); }

function showView(viewId){ document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view===viewId)); document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===viewId)); renderAll(); }
function setupTabs(){ document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>showView(btn.dataset.view))); }

async function restoreFormPrefs(){ $("subjectInput").value=await getSetting("lastSubject","형법"); $("sessionInput").value=await getSetting("lastSession",""); $("imageModeInput").value=await getSetting("lastImageMode","clear"); }

function imageToDataUrl(file,mode){ return new Promise((resolve,reject)=>{ if(mode==="original"){ const r=new FileReader(); r.onload=()=>resolve(r.result); r.onerror=()=>reject(r.error); r.readAsDataURL(file); return; } const img=new Image(), r=new FileReader(); r.onload=()=>{ img.onload=()=>{ const maxDim=mode==="small"?1500:2400, scale=Math.min(1,maxDim/Math.max(img.width,img.height)), w=Math.max(1,Math.round(img.width*scale)), h=Math.max(1,Math.round(img.height*scale)); const c=document.createElement("canvas"); c.width=w; c.height=h; const ctx=c.getContext("2d"); ctx.fillStyle="white"; ctx.fillRect(0,0,w,h); ctx.drawImage(img,0,0,w,h); resolve(c.toDataURL("image/jpeg",mode==="small"?0.72:0.88)); }; img.onerror=reject; img.src=r.result; }; r.onerror=()=>reject(r.error); r.readAsDataURL(file); }); }
function setupPasteZone(zoneId,fileId,previewId,kind){ const zone=$(zoneId), fileInput=$(fileId), preview=$(previewId); async function setImage(file){ if(!file)return; try{ const dataUrl=await imageToDataUrl(file,$("imageModeInput").value||"clear"); if(kind==="question")questionImageData=dataUrl; else modelImageData=dataUrl; preview.src=dataUrl; preview.classList.remove("hidden"); toast(`${kind==="question"?"문제":"모범답안"} 이미지 등록`); }catch(e){ console.error(e); toast("이미지를 처리하지 못했어"); } } zone.addEventListener("click",e=>{ if(e.target.tagName!=="INPUT")zone.focus(); }); zone.addEventListener("paste",async e=>{ const item=[...(e.clipboardData?.items||[])].find(i=>i.type.startsWith("image/")); if(!item)return; e.preventDefault(); await setImage(item.getAsFile()); }); fileInput.addEventListener("change",async()=>{ await setImage(fileInput.files?.[0]); fileInput.value=""; }); }

async function saveProblem(goNextEdit=false){ const editingId=$("editingId").value||"", existing=editingId?problems.find(p=>p.id===editingId):null; if(!questionImageData&&!existing?.questionImage){ toast("문제 이미지를 넣어줘"); return; } const subject=$("subjectInput").value, session=$("sessionInput").value.trim(), imageMode=$("imageModeInput").value; const problem={ id:editingId||uuid(), subject, session, title:$("titleInput").value.trim(), questionImage:questionImageData||existing?.questionImage||"", modelImage:modelImageData||existing?.modelImage||"", pointsText:$("pointsInput").value.trim(), points:pointsFromText($("pointsInput").value), modelText:$("modelTextInput").value.trim(), maxScore:Number($("maxScoreInput").value||0), timeLimitMin:Number($("timeLimitInput").value||0), order:existing?.order??Date.now(), createdAt:existing?.createdAt||nowIso(), updatedAt:nowIso() }; await put(STORES.problems,problem); await setSetting("lastSubject",subject); await setSetting("lastSession",session); await setSetting("lastImageMode",imageMode); await loadData(); toast(editingId?"수정 저장 완료":"문제 저장 완료"); if(goNextEdit&&editingId){ const sorted=[...problems].sort((a,b)=>(a.order??0)-(b.order??0)); const idx=sorted.findIndex(p=>p.id===editingId); if(idx>=0&&idx<sorted.length-1){ fillForm(sorted[idx+1]); return; } } if(editingId)fillForm(problem); else resetForm(false); renderAll(); }

function fillForm(p){ $("formTitle").textContent="문제 수정"; $("editingId").value=p.id; $("subjectInput").value=p.subject||"형법"; $("sessionInput").value=p.session||""; $("titleInput").value=p.title||""; $("maxScoreInput").value=p.maxScore||20; $("timeLimitInput").value=p.timeLimitMin||30; $("pointsInput").value=p.pointsText||(p.points||[]).join("\n"); $("modelTextInput").value=p.modelText||""; $("modelTextWrap").classList.toggle("hidden",!p.modelText); questionImageData=p.questionImage||""; modelImageData=p.modelImage||""; if(questionImageData){ $("questionPreview").src=questionImageData; $("questionPreview").classList.remove("hidden"); } else $("questionPreview").classList.add("hidden"); if(modelImageData){ $("modelPreview").src=modelImageData; $("modelPreview").classList.remove("hidden"); } else $("modelPreview").classList.add("hidden"); $("saveNextEditBtn").classList.remove("hidden"); showView("addView"); window.scrollTo(0,0); }
async function resetForm(restorePrefs=true){ $("formTitle").textContent="2차 문제 등록"; $("problemForm").reset(); $("editingId").value=""; $("maxScoreInput").value=20; $("timeLimitInput").value=30; questionImageData=""; modelImageData=""; $("questionPreview").classList.add("hidden"); $("modelPreview").classList.add("hidden"); $("modelTextWrap").classList.add("hidden"); $("saveNextEditBtn").classList.add("hidden"); if(restorePrefs)await restoreFormPrefs(); }

function makeButton(text,fn,cls=""){ const b=document.createElement("button"); b.type="button"; b.textContent=text; if(cls)b.className=cls; b.addEventListener("click",fn); return b; }
function problemCard(p,opts={}){ const last=lastAttempt(p.id), avg=avgElapsed(p.id); const div=document.createElement("div"); div.className="problem-card"; const checked=last&&Array.isArray(last.checkedPoints)?last.checkedPoints.filter(Boolean).length:null, total=(p.points?.length||pointsFromText(p.pointsText).length); div.innerHTML=`<h3>${escapeHtml(titleOf(p))}</h3><p class="meta">${escapeHtml(metaOf(p))}</p><div class="stat-line"><span class="badge">${escapeHtml(p.subject||"-")}</span><span class="badge">${escapeHtml(p.session||"회차 없음")}</span>${last?`<span class="badge">최근 ${fmtTime(last.elapsedMs)}</span>`:""}${avg?`<span class="badge">평균 ${fmtTime(avg)}</span>`:""}${last?.score!=null&&last.score!==""?`<span class="badge">최근 ${last.score}/${p.maxScore||last.maxScore||""}</span>`:""}${checked!=null?`<span class="badge">포인트 ${checked}/${total}</span>`:""}</div><div class="card-actions"></div>`; const actions=div.querySelector(".card-actions"); if(opts.practice)actions.append(makeButton("풀기",()=>startPractice([p.id],$("practiceMode").value||"outline"))); if(opts.review){ actions.append(makeButton("다시 풀기",()=>startPractice([p.id],"outline",{review:true}))); actions.append(makeButton("기록 보기",()=>showHistory(p.id),"secondary")); } if(opts.list){ actions.append(makeButton("수정",()=>fillForm(p),"secondary")); actions.append(makeButton("복제",async()=>{ const copy={...p,id:uuid(),title:`${p.title||titleOf(p)} 복사본`,createdAt:nowIso(),updatedAt:nowIso(),order:Date.now()}; await put(STORES.problems,copy); await loadData(); renderAll(); toast("복제 완료"); },"secondary")); actions.append(makeButton("삭제",async()=>{ if(!confirm("이 문제와 풀이기록을 삭제할까?"))return; await del(STORES.problems,p.id); for(const a of problemAttempts(p.id))await del(STORES.attempts,a.id); await loadData(); renderAll(); toast("삭제 완료"); },"danger small")); } return div; }

function renderPracticeList(){ const list=$("practiceProblemList"), arr=filterProblems({subject:$("practiceSubject").value,session:$("practiceSession").value}); list.innerHTML=""; if(!arr.length){ list.innerHTML=`<p class="hint">조건에 맞는 문제가 없어.</p>`; return; } arr.forEach(p=>list.append(problemCard(p,{practice:true}))); }
function renderList(){ const list=$("problemList"); let arr=filterProblems({subject:$("listSubject").value,session:$("listSession").value,search:$("listSearch").value}); const sort=$("listSort").value; if(sort==="new")arr=[...arr].sort((a,b)=>(b.createdAt||"").localeCompare(a.createdAt||"")); if(sort==="subject")arr=[...arr].sort((a,b)=>(a.subject||"").localeCompare(b.subject||"")||(a.session||"").localeCompare(b.session||"")); list.innerHTML=""; if(!arr.length){ list.innerHTML=`<p class="hint">등록된 문제가 없어.</p>`; return; } arr.forEach((p,i)=>{ const card=problemCard(p,{list:true}); card.querySelector("h3").textContent=`${i+1}. ${titleOf(p)}`; list.append(card); }); }
function renderReview(){ const list=$("reviewList"); let arr=filterProblems({subject:$("reviewSubject").value,session:$("reviewSession").value}); const type=$("reviewType").value; arr=arr.filter(p=>{ const last=lastAttempt(p.id); if(type==="all")return problemAttempts(p.id).length>0; if(!last)return false; if(type==="needed")return last.reviewNeeded===true||last.reviewNeeded==="true"; if(type==="lowScore")return isLowScore(last,p); if(type==="timeOver")return isTimeOver(last,p); if(type==="missedPoint")return hasMissedPoint(last,p); return true; }); const sort=$("reviewSort").value; if(sort==="scoreAsc")arr.sort((a,b)=>Number(lastAttempt(a.id)?.score??999)-Number(lastAttempt(b.id)?.score??999)); if(sort==="timeDesc")arr.sort((a,b)=>Number(lastAttempt(b.id)?.elapsedMs??0)-Number(lastAttempt(a.id)?.elapsedMs??0)); list.innerHTML=""; if(!arr.length){ list.innerHTML=`<p class="hint">복습 대상이 없어.</p>`; return; } arr.forEach(p=>list.append(problemCard(p,{review:true}))); }
function renderStats(){ const box=$("statsGrid"); const total=problems.length, done=new Set(attempts.map(a=>a.problemId)).size; const review=problems.filter(p=>{ const l=lastAttempt(p.id); return l&&(l.reviewNeeded===true||l.reviewNeeded==="true"); }).length; const avgScore=attempts.filter(a=>a.score!=null&&a.maxScore).map(a=>Number(a.score)/Number(a.maxScore)*100); const avg=avgScore.length?Math.round(avgScore.reduce((s,v)=>s+v,0)/avgScore.length):0; box.innerHTML=`<div class="stat-card">등록 문제<strong>${total}</strong></div><div class="stat-card">풀이 완료 문제<strong>${done}</strong></div><div class="stat-card">복습 필요<strong>${review}</strong></div><div class="stat-card">평균 득점률<strong>${avg}%</strong></div>`; }
function renderAll(){ renderPracticeList(); renderList(); renderReview(); renderStats(); renderContinueButton(); }

function showHistory(id){ const p=problems.find(x=>x.id===id), arr=problemAttempts(id); if(!arr.length)return toast("풀이 기록이 없어"); alert(`${titleOf(p)}\n\n`+arr.map((a,i)=>{ const checked=Array.isArray(a.checkedPoints)?a.checkedPoints.filter(Boolean).length:0,total=p.points?.length||pointsFromText(p.pointsText).length; return `${i+1}. ${dateLabel(a.completedAt)} / ${a.mode==="outline"?"목차":"실전"} / 시간 ${fmtTime(a.elapsedMs)} / 점수 ${a.score??"-"}${p.maxScore?"/"+p.maxScore:""} / 포인트 ${checked}/${total} / 복습 ${a.reviewNeeded?"필요":"불필요"}`; }).join("\n")); }

function chooseRandom(arr,n){ return [...arr].sort(()=>Math.random()-0.5).slice(0,Math.min(n,arr.length)); }
function startRandom(reviewOnly=false){ let arr=filterProblems({subject:$("practiceSubject").value,session:$("practiceSession").value}); if(reviewOnly)arr=arr.filter(p=>{ const l=lastAttempt(p.id); return l&&(l.reviewNeeded===true||l.reviewNeeded==="true"); }); if(!arr.length)return toast(reviewOnly?"복습필요 문제가 없어":"조건에 맞는 문제가 없어"); const picks=chooseRandom(arr,Number($("practiceCount").value||1)); startPractice(picks.map(p=>p.id),$("practiceMode").value||"outline",{review:reviewOnly}); }
function startPractice(ids,mode="outline",options={}){ if(!ids?.length)return toast("풀 문제가 없어"); activeSession={ids,index:0,mode,review:!!options.review,answerText:"",startedAt:Date.now(),questionStart:Date.now(),elapsedBase:0,currentProblemId:ids[0],completedAttemptIds:[],draft:false}; currentAttemptSnapshot=lastAttempt(ids[0])||null; saveActiveDraft(); openPracticeProblem(); }
function openPracticeProblem(){ const p=problems.find(x=>x.id===activeSession?.currentProblemId); if(!p)return finishPractice(); activeSession.questionStart=Date.now(); $("practiceOverlay").classList.remove("hidden"); $("essayTitle").textContent=titleOf(p); $("essayMeta").textContent=metaOf(p); $("essayProgress").textContent=`${activeSession.index+1}/${activeSession.ids.length} · ${activeSession.mode==="outline"?"목차연습":"실전답안"}`; $("answerLabel").textContent=activeSession.mode==="outline"?"내 목차/쟁점":"내 답안"; $("answerText").value=activeSession.answerText||""; $("essayQuestionImage").src=p.questionImage||""; zoom=1; applyZoom(); updateTimer(); clearInterval(timerHandle); timerHandle=setInterval(updateTimer,500); }
function elapsedNow(){ return activeSession?(activeSession.elapsedBase||0)+(Date.now()-activeSession.questionStart):0; }
function updateTimer(){ if(!activeSession)return; const p=problems.find(x=>x.id===activeSession.currentProblemId), elapsed=elapsedNow(); $("essayTimer").textContent=fmtTime(elapsed); const limit=Number(p?.timeLimitMin||0)*60000; $("limitTimer").textContent=limit?(limit>=elapsed?`남은 ${fmtTime(limit-elapsed)}`:`초과 ${fmtTime(elapsed-limit)}`):""; }
function pausePractice(){ if(!activeSession)return; activeSession.elapsedBase=elapsedNow(); activeSession.answerText=$("answerText").value; activeSession.draft=true; clearInterval(timerHandle); timerHandle=null; saveActiveDraft(); $("practiceOverlay").classList.add("hidden"); renderAll(); toast("중단 저장 완료"); }
function submitPractice(){ if(!activeSession)return; activeSession.elapsedBase=elapsedNow(); activeSession.answerText=$("answerText").value; clearInterval(timerHandle); timerHandle=null; const p=problems.find(x=>x.id===activeSession.currentProblemId); if(!p)return; $("scoreOverlay").classList.remove("hidden"); $("scoreMeta").textContent=`${titleOf(p)} · 풀이시간 ${fmtTime(activeSession.elapsedBase)}`; $("ownAnswerView").textContent=activeSession.answerText||"(작성한 답안 없음)"; if(p.modelImage){ $("scoreModelImage").src=p.modelImage; $("scoreModelImage").classList.remove("hidden"); } else $("scoreModelImage").classList.add("hidden"); $("scoreModelText").textContent=p.modelText||""; $("scoreInput").value=""; $("scoreInput").max=p.maxScore||""; $("ratingInput").value="중"; $("reviewNeededInput").value="true"; $("completionInput").value=activeSession.mode==="outline"?"목차만":"완성"; $("scoreNoteInput").value=""; renderChecklist(p); renderTimeCompare(p); }
function renderChecklist(p){ const box=$("pointChecklist"), points=p.points?.length?p.points:pointsFromText(p.pointsText); box.innerHTML=""; if(!points.length){ box.innerHTML=`<p class="hint">등록된 채점포인트가 없어.</p>`; return; } points.forEach((point,i)=>{ const row=document.createElement("label"); row.className="check-item"; row.innerHTML=`<input type="checkbox" data-point-idx="${i}" /> <span>${escapeHtml(point)}</span>`; box.append(row); }); }
function renderTimeCompare(p){ const last=currentAttemptSnapshot||lastAttempt(p.id), avg=avgElapsed(p.id), box=$("timeCompareBox"); if(!last&&!avg){ box.classList.add("hidden"); return; } const now=activeSession.elapsedBase, diff=last?now-last.elapsedMs:0; box.innerHTML=`<strong>이전 풀이시간 비교</strong><br/>이번: ${fmtTime(now)}<br/>${last?`이전 최근: ${fmtTime(last.elapsedMs)} · ${diff<=0?"단축":"증가"} ${fmtTime(Math.abs(diff))}<br/>`:""}${avg?`이전 평균: ${fmtTime(avg)}`:""}`; box.classList.remove("hidden"); }
async function saveAttempt(){ if(!activeSession)return; const p=problems.find(x=>x.id===activeSession.currentProblemId); if(!p)return; const attempt={id:uuid(),problemId:p.id,subject:p.subject,session:p.session,mode:activeSession.mode,answerText:activeSession.answerText||"",elapsedMs:activeSession.elapsedBase,score:$("scoreInput").value===""?null:Number($("scoreInput").value),maxScore:p.maxScore||0,checkedPoints:[...document.querySelectorAll("#pointChecklist input[type='checkbox']")].map(x=>x.checked),rating:$("ratingInput").value,reviewNeeded:$("reviewNeededInput").value==="true",completion:$("completionInput").value,note:$("scoreNoteInput").value.trim(),completedAt:nowIso()}; await put(STORES.attempts,attempt); activeSession.completedAttemptIds.push(attempt.id); await loadData(); saveActiveDraft(); toast("풀이 기록 저장 완료"); }
async function saveAttemptAndNext(){ await saveAttempt(); nextPractice(); }
function nextPractice(){ if(!activeSession)return; if(activeSession.index>=activeSession.ids.length-1){ finishPractice(); return; } activeSession.index++; activeSession.currentProblemId=activeSession.ids[activeSession.index]; activeSession.answerText=""; activeSession.elapsedBase=0; currentAttemptSnapshot=lastAttempt(activeSession.currentProblemId)||null; $("scoreOverlay").classList.add("hidden"); saveActiveDraft(); openPracticeProblem(); }
function finishPractice(){ clearInterval(timerHandle); timerHandle=null; activeSession=null; currentAttemptSnapshot=null; localStorage.removeItem("essayActiveSession_v2"); $("practiceOverlay").classList.add("hidden"); $("scoreOverlay").classList.add("hidden"); renderAll(); toast("연습 종료"); }
function saveActiveDraft(){ if(!activeSession)return; activeSession.answerText=$("answerText")?.value??activeSession.answerText??""; localStorage.setItem("essayActiveSession_v2",JSON.stringify(activeSession)); renderContinueButton(); }
function loadActiveDraft(){ try{ const raw=localStorage.getItem("essayActiveSession_v2"); if(!raw)return null; const s=JSON.parse(raw); if(!s?.currentProblemId||!problems.some(p=>p.id===s.currentProblemId))return null; return s; }catch{return null;} }
function continueDraft(){ const s=loadActiveDraft(); if(!s)return toast("이어풀 문제가 없어"); activeSession=s; activeSession.questionStart=Date.now(); currentAttemptSnapshot=lastAttempt(activeSession.currentProblemId)||null; openPracticeProblem(); }
function renderContinueButton(){ $("continueDraftBtn").classList.toggle("hidden",!loadActiveDraft()); }

function applyZoom(){ $("essayQuestionImage").style.width=`${Math.round(100*zoom)}%`; }
function fitZoom(){ zoom=1; applyZoom(); setTimeout(()=>{ const sc=$("imageScroller"), img=$("essayQuestionImage"); if(!img.naturalWidth||!sc.clientWidth)return; zoom=Math.max(0.2,Math.min(1,(sc.clientWidth-20)/img.naturalWidth)); applyZoom(); },0); }

async function exportBackup(){ const settings=await getAll(STORES.settings); const payload={app:"essay-exam-practice",version:2,exportedAt:nowIso(),problems,attempts,settings}; const blob=new Blob([JSON.stringify(payload)],{type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=`essay_exam_backup_${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(a.href); }
async function importBackup(file){ if(!file)return; const data=JSON.parse(await file.text()); if(!Array.isArray(data.problems))throw new Error("Invalid backup"); if(!confirm("현재 데이터에 백업 데이터를 합쳐서 복원할까? 같은 ID는 덮어쓰기 돼."))return; for(const p of data.problems)await put(STORES.problems,p); for(const a of(data.attempts||[]))await put(STORES.attempts,a); for(const s of(data.settings||[]))if(s.key)await put(STORES.settings,s); await loadData(); renderAll(); toast("복원 완료"); }
async function wipeAll(){ if(!confirm("모든 문제와 풀이기록을 삭제할까? 백업 없으면 복구할 수 없어."))return; await clearStore(STORES.problems); await clearStore(STORES.attempts); await clearStore(STORES.settings); localStorage.removeItem("essayActiveSession_v2"); await loadData(); await restoreFormPrefs(); renderAll(); toast("전체 삭제 완료"); }


let deferredInstallPrompt = null;
function setupInstallButton() {
  const installBtn = $("installBtn");
  if (!installBtn) return;

  window.addEventListener("beforeinstallprompt", (event) => {
    event.preventDefault();
    deferredInstallPrompt = event;
    installBtn.classList.remove("hidden");
  });

  installBtn.addEventListener("click", async () => {
    if (!deferredInstallPrompt) {
      toast("Chrome 메뉴에서 홈 화면에 추가를 눌러줘");
      return;
    }
    deferredInstallPrompt.prompt();
    await deferredInstallPrompt.userChoice.catch(() => null);
    deferredInstallPrompt = null;
    installBtn.classList.add("hidden");
  });

  window.addEventListener("appinstalled", () => {
    deferredInstallPrompt = null;
    installBtn.classList.add("hidden");
    toast("앱 설치 완료");
  });
}

function setupEvents(){ setupTabs(); ["practiceSubject","practiceSession","practiceMode","practiceCount","listSubject","listSession","listSearch","listSort","reviewSubject","reviewSession","reviewType","reviewSort"].forEach(id=>{ $(id).addEventListener("input",renderAll); $(id).addEventListener("change",renderAll); }); setupPasteZone("questionPaste","questionFile","questionPreview","question"); setupPasteZone("modelPaste","modelFile","modelPreview","model"); $("problemForm").addEventListener("submit",async e=>{ e.preventDefault(); await saveProblem(false); }); $("saveNextEditBtn").addEventListener("click",async()=>saveProblem(true)); $("resetFormBtn").addEventListener("click",async()=>resetForm(true)); $("toggleModelTextBtn").addEventListener("click",()=>$("modelTextWrap").classList.toggle("hidden")); $("startRandomBtn").addEventListener("click",()=>startRandom(false)); $("startReviewRandomBtn").addEventListener("click",()=>startRandom(true)); $("continueDraftBtn").addEventListener("click",continueDraft); document.querySelectorAll("[data-quick-subject]").forEach(b=>b.addEventListener("click",()=>{ $("practiceSubject").value=b.dataset.quickSubject; startRandom(false); })); $("answerText").addEventListener("input",()=>{ if(!activeSession)return; activeSession.answerText=$("answerText").value; saveActiveDraft(); }); $("pauseBtn").addEventListener("click",pausePractice); $("submitBtn").addEventListener("click",submitPractice); $("zoomFitBtn").addEventListener("click",fitZoom); $("zoomInBtn").addEventListener("click",()=>{ zoom=Math.min(3,zoom+0.15); applyZoom(); }); $("zoomOutBtn").addEventListener("click",()=>{ zoom=Math.max(0.2,zoom-0.15); applyZoom(); }); $("closeScoreBtn").addEventListener("click",()=>{ $("scoreOverlay").classList.add("hidden"); if(activeSession){ activeSession.questionStart=Date.now(); clearInterval(timerHandle); timerHandle=setInterval(updateTimer,500); $("practiceOverlay").classList.remove("hidden"); } }); $("saveAttemptBtn").addEventListener("click",saveAttempt); $("nextEssayBtn").addEventListener("click",saveAttemptAndNext); $("finishEssayBtn").addEventListener("click",async()=>{ await saveAttempt(); finishPractice(); }); $("exportBtn").addEventListener("click",exportBackup); $("importInput").addEventListener("change",async()=>{ try{ await importBackup($("importInput").files?.[0]); }catch(e){ console.error(e); toast("복원 실패"); } $("importInput").value=""; }); $("wipeBtn").addEventListener("click",wipeAll); $("essayQuestionImage").addEventListener("load",fitZoom); }

async function init(){ db=await openDB(); await loadData(); await restoreFormPrefs(); setupEvents(); setupInstallButton(); renderAll(); if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js?v=3").catch(()=>{}); }
init().catch(err=>{ console.error(err); alert("앱 초기화 실패: "+err.message); });
